name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Test code 
        run: npm test

      - name: Test deploy 
        run: npm run test:deploy

      - name: Codecov
        uses: codecov/codecov-action@v3.1.1